### PR TITLE
Update introduction based on feedback

### PR DESCRIPTION
**Pull request by macaptain**
A bit more blurb on Ironic based on the feedback in https://github.com/metal3-io/metal3-docs/pull/236

### CODE REVIEW

**Review by furkatgofurov7 — COMMENTED** [review]
Lgtm

**Review by smoshiur1237 — APPROVED** [review]
LGTM

**Review by fmuyassarov — COMMENTED** [review]
/lgtm

**Comment by Sunnatillo** [comment]
LGTM

**Review by Sunnatillo — APPROVED** [review]
LGTM

**Pull request merged**
