### PR TITLE
Add metal3-dev-env high level architecture image

### PR DESCRIPTION
**Pull request by fmuyassarov**
This image is expected to be used by try-it.md

### CODE REVIEW

**Comment by russellb** [comment]
nice work.
/approve
/lgtm

**Comment by alosadagrande** [comment]
Is it me or the network names and IP addresses in the diagram do not match. This is the network names and IP networks associated in my lab env:

```
[root@eko1 metal3-dev-env]# virsh net-dhcp-leases default
 Expiry Time          MAC address        Protocol  IP address                Hostname        Client ID or DUID
-------------------------------------------------------------------------------------------------------------------
 2020-01-28 17:19:24  f8:46:ab:4b:56:ef  ipv4      192.168.122.157/24        minikube        01:f8:46:ab:4b:56:ef



[root@eko1 metal3-dev-env]# virsh net-dhcp-leases minikube-net
 Expiry Time          MAC address        Protocol  IP address                Hostname        Client ID or DUID
-------------------------------------------------------------------------------------------------------------------
 2020-01-28 17:19:23  28:a8:10:4e:e7:53  ipv4      192.168.39.101/24         minikube        01:28:a8:10:4e:e7:53



[root@eko1 metal3-dev-env]# virsh net-dhcp-leases baremetal
 Expiry Time          MAC address        Protocol  IP address                Hostname        Client ID or DUID
-------------------------------------------------------------------------------------------------------------------
 2020-01-28 17:17:10  00:00:e0:4b:24:91  ipv4      192.168.111.21/24         node-1          -
 2020-01-28 17:16:51  00:00:e0:4b:24:95  ipv4      192.168.111.22/24         node-2          -
 2020-01-28 16:59:49  52:54:00:b1:69:e0  ipv4      192.168.111.29/24         minikube        01:52:54:00:b1:69:e0



[root@eko1 metal3-dev-env]# virsh net-dhcp-leases provisioning
 Expiry Time          MAC address        Protocol  IP address                Hostname        Client ID or DUID
-------------------------------------------------------------------------------------------------------------------
```

Provisioning net which is not shown above is:

```
[root@eko1 metal3-dev-env]# ifconfig provisioning
provisioning: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.22.0.1  netmask 255.255.255.0  broadcast 172.22.0.255

```

**Comment by Xenwar** [comment]
> Is it me or the network names and IP addresses in the diagram **already merged** do not match. These are the network names and IP networks associated in my lab env (default deploy):
> 

I agree. 
There are some mismatches. 
And, `minikube` should be `minikube-net`

**Comment by fmuyassarov** [comment]
> Is it me or the network names and IP addresses in the diagram **already merged** do not match. These are the network names and IP networks associated in my lab env (default deploy):
> 
> ```
> [root@eko1 metal3-dev-env]# virsh net-dhcp-leases default
>  Expiry Time          MAC address        Protocol  IP address                Hostname        Client ID or DUID
> -------------------------------------------------------------------------------------------------------------------
>  2020-01-28 17:19:24  f8:46:ab:4b:56:ef  ipv4      192.168.122.157/24        minikube        01:f8:46:ab:4b:56:ef
> 
> 
> 
> [root@eko1 metal3-dev-env]# virsh net-dhcp-leases minikube-net
>  Expiry Time          MAC address        Protocol  IP address                Hostname        Client ID or DUID
> -------------------------------------------------------------------------------------------------------------------
>  2020-01-28 17:19:23  28:a8:10:4e:e7:53  ipv4      192.168.39.101/24         minikube        01:28:a8:10:4e:e7:53
> 
> 
> 
> [root@eko1 metal3-dev-env]# virsh net-dhcp-leases baremetal
>  Expiry Time          MAC address        Protocol  IP address                Hostname        Client ID or DUID
> -------------------------------------------------------------------------------------------------------------------
>  2020-01-28 17:17:10  00:00:e0:4b:24:91  ipv4      192.168.111.21/24         node-1          -
>  2020-01-28 17:16:51  00:00:e0:4b:24:95  ipv4      192.168.111.22/24         node-2          -
>  2020-01-28 16:59:49  52:54:00:b1:69:e0  ipv4      192.168.111.29/24         minikube        01:52:54:00:b1:69:e0
> 
> 
> 
> [root@eko1 metal3-dev-env]# virsh net-dhcp-leases provisioning
>  Expiry Time          MAC address        Protocol  IP address                Hostname        Client ID or DUID
> -------------------------------------------------------------------------------------------------------------------
> ```
> 
> Provisioning net which is not shown above is:
> 
> ```
> [root@eko1 metal3-dev-env]# ifconfig provisioning
> provisioning: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 172.22.0.1  netmask 255.255.255.0  broadcast 172.22.0.255
> ```
> 
> cc/ @fmuyassarov @russellb

Sorry, for the mismatch.  There is a fix for that now. 
[#PR70](https://github.com/metal3-io/metal3-docs/pull/70
)

**Pull request merged**
