### PR TITLE
update repositories and ALL-OWNERS

### PR DESCRIPTION
**Pull request by tuminoid**
Add missing repositories:
 - ironic-hardware-inventory-recorder-image

Remove (soon to be archived) repositories:
 - static-ip-manager-image

Update ALL-OWNERS with the script.

### CODE REVIEW

**Comment by tuminoid** [comment]
/hold

SIPM is to be removed next week.

**Comment by tuminoid** [comment]
/hold cancel

Deadline has passed, repo will be archived.

**Review by furkatgofurov7 — APPROVED** [review]
Thank you!

/approve

**Pull request merged**
