### PR TITLE
Presentations framework proposal with a sample presentation

### PR DESCRIPTION
**Pull request by hroyrh**
For presentations and their framework proposal - I have added a sample presentation, Metal3 high level overview, in the new framework format. I have used revealjs to create it but the content is mostly markdown, so you should be able to reuse it with some other markdown-supporting frameworks as well. I have included a readme file listing steps to deploy the presentation and export it to pdf format.
Please review it and share any feedback you might have.

### CODE REVIEW

**Comment by maelk** [comment]
This looks good. Could you maybe add a couple of screenshots of the example presentation to the PR ?

**Comment by hroyrh** [comment]
@maelk I have included a few screenshots for the sample presentation, let me know if they look good.

**Comment by stbenjam** [comment]
As discussed during weekly meeting, merging manually due to Prow outage.

**Pull request merged**
