### PR TITLE
Draft CNCF sandbox application

### PR DESCRIPTION
**Pull request by russellb**
Following PR #77 which proposed that we apply for metal3-io to join
the CNCF Sandbox, this PR includes a draft of the actual application
to be submitted to the CNCF TOC.

Other CNCF Sandbox proposals can be found here:
https://github.com/cncf/toc/tree/master/proposals/sandbox

The project proposal process is covered here:
https://github.com/cncf/toc/blob/master/process/project_proposals.adoc

For more discussion on this for metal3-io, see the
design/foundation-proposal.md doc from #77.

### CODE REVIEW

**Comment by russellb** [comment]
/hold

hold just to ensure multiple people get a chance to review

**Comment by kfox1111** [comment]
lgtm

**Comment by fmuyassarov** [comment]
+1

**Comment by stbenjam** [comment]
lgtm

**Comment by intlabs** [comment]
lgtm

**Comment by stbenjam** [comment]
@jtwill98 This caught me offguard at first too, but the document is asciidoc not markdown. While it probably partially renders as markdown it won't understand the link syntax.

**Comment by mattmceuen** [comment]
LGTM

**Comment by maelk** [comment]
lgtm, thank you for drafting this

**Comment by jtwill98** [comment]
> @jtwill98 This caught me offguard at first too, but the document is asciidoc not markdown. While it probably partially renders as markdown it won't understand the link syntax.

It that case, this LGTM  +1

**Comment by russellb** [comment]
/hold cancel

I think we can merge this.  I will submit this application and post a link here.

**Comment by russellb** [comment]
Application posted here: https://github.com/cncf/toc/pull/408

**Pull request merged**
