### PR TITLE
add broken link checker action

### PR DESCRIPTION
**Pull request by tuminoid**
Add broken link checker action from CAPM3.

### CODE REVIEW

**Review by kashifest — APPROVED** [review]

**Review by smoshiur1237 — APPROVED** [review]
/lgtm

**Review by furkatgofurov7 — COMMENTED** [review]
@tuminoid is there an example run of this somewhere (possibly fork)?

**Comment by tuminoid** [comment]
> @tuminoid is there an example run of this somewhere (possibly fork)?

There is specific `if:` in the workflow to prevent it from running on forks, but  you can run it with `gh` CLI using extension `act` for example. It fails 10-12 URLs right now, which is why I held it. I'm working on PR to fix those links before we can merge this.

**Comment by furkatgofurov7** [comment]
> There is specific `if:` in the workflow to prevent it from running on forks, but you can run it with `gh` CLI using extension `act` for example. It fails 10-12 URLs right now, which is why I held it. I'm working on PR to fix those links before we can merge this.

Used act before, cool stuff. In any case this should be good to go IMO.

/approve

**Comment by tuminoid** [comment]
This is still pending fixing currently broken links before it can be activated.

**Comment by tuminoid** [comment]
/lifecycle frozen
This is pending multiple fixing PRs before it can be merged, let's se it frozen to avoid going stale.

**Comment by tuminoid** [comment]
/remove-lifecycle stale
Still pending fixes to broken links to be activated

**Comment by tuminoid** [comment]
This can be redone, if the broken links get eventually fixed. Closing for now.

/close

**Pull request closed without merging**
