### PR TITLE
remove outdated CoC and link the new one

### PR DESCRIPTION
**Pull request by tuminoid**
CoC has been updated to [CNCF Code of Conduct v1.3 in the community repo](https://github.com/metal3-io/community/pull/8). CoC document in this repo is thus outdated and duplicate.

/hold
until community repo PR has been merged.

### CODE REVIEW

**Review by Rozzii — APPROVED** [review]
/lgtm

**Comment by tuminoid** [comment]
/unhold
CoC update has merged in community repo.

**Pull request merged**
