### PR TITLE
add spellchecker, and fix pre-existing issues

### PR DESCRIPTION
**Pull request by tuminoid**
Add spellchecker to keep our documentation in good shape. Fix pre-existing issues, and add some words to the words list. The base word list is imported from website repository, and then cleaned up from the words not appearing in this repository.

Add shellcheck to lint these hack scripts.

Needs https://github.com/metal3-io/project-infra/pull/625 to merge first.
/hold

### CODE REVIEW

**Review by kashifest — COMMENTED** [review]
/approve

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
/retest
With new checks enabled.

**Comment by tuminoid** [comment]
/unhold
Good to go.

**Pull request merged**
