### PR TITLE
Update the status of automated disk cleaning proposal

### PR DESCRIPTION
**Pull request by fmuyassarov**
Update the status of _Allow disable automated disk cleaning_ proposal, since implantation PRs got merged.
https://github.com/metal3-io/baremetal-operator/pull/784
https://github.com/metal3-io/cluster-api-provider-metal3/pull/156

### CODE REVIEW

**Review by furkatgofurov7 — COMMENTED** [review]
This has been implemented, LGTM.

**Comment by fmuyassarov** [comment]
@hardys would you mind to approve this if looks good?

**Pull request merged**
