### PR TITLE
Broken links fix

### PR DESCRIPTION
**Pull request by SafeEHA**
Under 4.1 Install cluster-api metal3 provider [TODO](https://book.metal3.io/capm3/TODO) returns an error when clicked so i found the correct [link](https://book.metal3.io/ironic/ironic_installation.html) and updated it

In 4.3.1 Remediation, the links [remediation](https://cluster-api.sigs.k8s.io/tasks/healthcheck.html) and [CAPI MHC](https://cluster-api.sigs.k8s.io/tasks/healthcheck.html) were broken. I replaced them with [this](https://cluster-api.sigs.k8s.io/tasks/automated-machine-management/healthchecking.html) this page

### CODE REVIEW

**Comment by SafeEHA** [comment]
Hello @furkatgofurov7 
So I tried squashing the prev commits but it was proving a bit difficult, I then decided to create a new branch locally and made changes there, I hope this is fine?

cc @elfosardo

**Comment by dtantsur** [comment]
This PR involves 3 unrelated commits, why is that?

**Comment by elfosardo** [comment]
@SafeEHA I think you're applying your patch to a wrong commit or the rebase went somewhat wrong
please fix it

**Comment by SafeEHA** [comment]
Hello @elfosardo @dtantsur 
I have removed the other commits, please review

**Comment by tuminoid** [comment]
> I have tried deleting the binary files locally but I can't seem to find them, please can you assist me on how to go about this @tuminoid I wanted to delete the files individually from GitHub but I doubt that would help much and would definitely be too messy

In your fork's `patch3` branch, do `git rm -f <path to binary file>` for each file, and amend the commit with 'git commit -a --amend`.

**Comment by SafeEHA** [comment]
I have successfully removed them...thanks @tuminoid

**Comment by tuminoid** [comment]
> I have successfully removed them...thanks @tuminoid

Now squash the commits please, then we're good to merge.

**Comment by SafeEHA** [comment]
Hello @tuminoid 
Thank you so much for all your help 
I want to notify you that in trying to squash the commits I created a conflict and I can't seem to resolve it, also git rebase -i HEAD~3 currently in my local environment returns 7-8 other commits instead of the exact number I specify.

I am looking at creating a new PR, which meets all the requirements since I am aware of those now so hopefully the merge can be done today

**Pull request closed without merging**
