### PR TITLE
use docker.io consistently as image registry

### PR DESCRIPTION
**Pull request by tuminoid**
Use docker.io consistently as image registry.

### CODE REVIEW

**Review by kashifest — APPROVED** [review]

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Review by lentzi90 — APPROVED** [review]

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Review by kashifest — APPROVED** [review]
/lgtm

**Review by furkatgofurov7 — APPROVED** [review]

**Pull request merged**
