### PR TITLE
Add BMO release-0.4 and release-0.3 branch in version support guide

### PR DESCRIPTION
**Pull request by kashifest**
As the title says

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Review by smoshiur1237 — APPROVED** [review]
LGTM

**Review by Rozzii — APPROVED** [review]
/approve

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by Rozzii — APPROVED** [review]

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Pull request merged**
