### PR TITLE
fix and simplify all-owners script

### PR DESCRIPTION
**Pull request by tuminoid**
Noticed with @kashifest in #366 that the script isn't working right. Fix and simplify the script. 

1. remove emeritus_approvers from the list, they're not active maintainers
2. simplify the primary branch detection
3. add new repo utility-images
4. remove lower casing the github names, some have legit caps there like "Rozzii", added explicit sorting option to keep the sorting the same in Linux and Mac

### CODE REVIEW

**Review by kashifest — COMMENTED** [review]
/approve

**Comment by kashifest** [comment]
cc @Rozzii

**Review by Rozzii — APPROVED** [review]
/approve

**Pull request merged**
