### PR TITLE
Fix dead links at cap3-remidiation-controller.md

### LINKED ISSUE #442: Fix dead links at capm3-remediation-controller-proposal.md
```
| FILE: ./design/cluster-api-provider-metal3/capm3-remediation-controller-proposal.md
| [✖] https://cluster-api.sigs.k8s.io/tasks/healthcheck.html
| [✖] https://github.com/metal3-io/metal3-docs/blob/main/design/baremetal-operator/re-introspection-interface.md
| 
| 6 links checked.
| 
| ERROR: 2 dead links found!
| [✖] https://cluster-api.sigs.k8s.io/tasks/healthcheck.html → Status: 404
| [✖] https://github.com/metal3-io/metal3-docs/blob/main/design/baremetal-operator/re-introspection-interface.md → Status: 404
```

/triage accepted
/help
/good-first-issue

Split from https://github.com/metal3-io/metal3-docs/issues/328

### PR DESCRIPTION
**Pull request by ayushrakesh**
#Fix dead links at specified file -> [./design/cluster-api-provider-metal3/capm3-remediation-controller-proposal.md](https://github.com/metal3-io/metal3-docs/blob/main/design/cluster-api-provider-metal3/capm3-remediation-controller-proposal.md)

| [✖] https://cluster-api.sigs.k8s.io/tasks/healthcheck.html
changed to
https://cluster-api.sigs.k8s.io/tasks/automated-machine-management/healthchecking

| [✖] https://github.com/metal3-io/metal3-docs/blob/main/design/baremetal-operator/re-introspection-interface.md
changed to
https://github.com/metal3-io/metal3-docs/blob/main/design/baremetal-operator/inspection-api.md

# Fixes #442

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/lgtm

Thanks for the contribution!

**Review by Rozzii — COMMENTED** [review]
/lgtm

**Pull request merged**
