### PR TITLE
User guide: clean-up the BMO features

### PR DESCRIPTION
**Pull request by dtantsur**
Split the features into basic (what most operators may use) and advanced (only for very specific use cases). Clean-up formatting, provide up-to-date information and examples, remove redundant text.

Reworked items:
- **User guide: clean-up cleaning documentation**
- **User guide: clean-up inspection documentation**
- **User guide: clean-up reboot documentation**
- **User guide: clean-up live-iso documentation**

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by tuminoid — COMMENTED** [review]
LGTM. Letting others review too.

Thanks for pushing all these user guide improvements!

**Review by Rozzii — COMMENTED** [review]
/lgtm

**Pull request merged**
