### PR TITLE
Add Metal3 architectural diagrams

### PR DESCRIPTION
**Pull request by fmuyassarov**
Co-authored-by: Maël Kimmerlin <mael.kimmerlin@est.tech>

### CODE REVIEW

**Comment by maelk** [comment]
Would you mind giving more meaningful names to the files please ? Also, maybe svg or png would be a better format if possible

**Comment by hroyrh** [comment]
A small comment - in  Slide2.jpg image shouldn't we use "Control Plane Nodes" instead of "Masters".

**Comment by fmuyassarov** [comment]
> Would you mind giving more meaningful names to the files please ? Also, maybe svg or png would be a better format if possible

Oh forgot that. Thanks.

**Comment by fmuyassarov** [comment]
> A small comment - in Slide2.jpg image shouldn't we use "Control Plane Nodes" instead of "Masters".

Thanks. fixed.

**Comment by dhellmann** [comment]
These look good to me. Are we ready to merge them?

/approve

**Comment by fmuyassarov** [comment]
> For the images/architectural diagrams/components.svg I think it would help to update the diagram to reflect 2 controllers - KCP and CABPK

CAPBK is already there on picture, on the right most block. For KCP we didn't include it because here we wanted to show the references for mainly cluster and machines objects. We could add later another diagram with all the CAPI objects like KCP, MachineHealthCheck, etc.

**Comment by fmuyassarov** [comment]
> These look good to me. Are we ready to merge them?
> 
> /approve

Yes I think.

**Pull request merged**
