### PR TITLE
Add ADOPTERS file

### PR DESCRIPTION
**Pull request by fmuyassarov**
Add `ADOPTERS.md` file and add Ericsson as one of the
adopters. We plan to reach out our community and users
and ask them to submit pull requests to include their names
in this list. This was initiated while writing Metal3.io Annual
[review](https://docs.google.com/document/d/1RDu4oY_9c9xXvkI74peg6oXxx1cArXMXB3uyMaFT0aw/edit#) for CNCF, and we plan to include the link to this
document in that report.

Also, disable `MD013` markdown rule for table length.

### CODE REVIEW

**Comment by kashifest** [comment]
Looks good to me. I dont know if I have lgtm rights. 
/lgtm

**Comment by russellb** [comment]
added Red Hat in #198

**Pull request merged**
