### PR TITLE
Revert "Go preprocessor to find and replace releasetags"

### PR DESCRIPTION
**Pull request by dtantsur**
This reverts commit 5e9b9585518c94475f16a2c154ac37200a8af60f.

This change currently causes a crash when building the user guide:

```
2024-05-03 16:55:51 [INFO] (mdbook::book): Book building has started
2024-05-03 16:55:51 [INFO] (mdbook::book): Running the html backend
thread 'main' panicked at '', src/utils/fs.rs:45:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::panicking::panic_display
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:64:5
   3: core::option::expect_failed
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/option.rs:1638:5
   4: <mdbook::renderer::html_handlebars::hbs_renderer::HtmlHandlebars as mdbook::renderer::Renderer>::render
   5: mdbook::book::MDBook::build
   6: mdbook::main
```

Reproducible both locally and in the CI.

Signed-off-by: Dmitry Tantsur <dtantsur@protonmail.com>

### CODE REVIEW

**Comment by dtantsur** [comment]
I'm sorry @peppi-lotta, but unless we have a quick idea how to fix the build, the PR needs to be reverted.

/cc @adilGhaffarDev @kashifest

**Comment by lentzi90** [comment]
Weird! Looks like everything was fine in https://github.com/metal3-io/metal3-docs/pull/386. Also, this code is mostly coming from [CAPI](https://github.com/kubernetes-sigs/cluster-api/blob/main/hack/tools/mdbook/releaselink/releaselink.go) as far as I know. I wonder what changed :thinking:

**Comment by lentzi90** [comment]
I found the issue. Fix in https://github.com/metal3-io/metal3-docs/pull/423
Although maybe more like a workaround. It would be nice to make the preprocessor more robust or improve the error message...

**Comment by dtantsur** [comment]
I agree, we need better diagnostics. But the revert is no longer needed, thanks all!

**Comment by peppi-lotta** [comment]
I added to metal3-docs a [warning](https://github.com/metal3-io/metal3-docs/pull/386) about links without a path causing an error and created an [issue](https://github.com/rust-lang/mdBook/issues/2369) in mdbook about it. I had noticed this an added a note in the README.md but obviously that was too hidden :sweat_smile:. CAPI has this same problem but they just aren't using Draft Chapters aka links without a path in SUMMARY.md.

**Pull request closed without merging**
