### PR TITLE
Update the root and design OWNERS

### PR DESCRIPTION
**Pull request by dtantsur**
Root OWNERS:
- Remove Andrea who is no longer active on the project.

Design OWNERS:
- Remove Andrea and Russell who are no longer active on the project.
- Add Riccardo and Lennart to reviewers. Both have provided excellent
  feedback recently, both have good knowledge of respective areas of
  Metal3.
- Promote Kashif and Adam to approvers. They have been critical contributors
  to Metal3 and reviewers for a long time.

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Comment by dtantsur** [comment]
FYI @kashifest @Rozzii

**Comment by kashifest** [comment]
> FYI @kashifest @Rozzii

Thanks @dtantsur

**Pull request merged**
