### PR TITLE
Remove extra OWNERS files and propose more reviewers in root OWNERS

### PR DESCRIPTION
**Pull request by kashifest**
Theres no need to have these extra OWNERS files as the `design` directory has its own and it does not inherit parent OWNER file. Removing these reduces confusion. 

Also proposing more reviewers in the root OWNERS and this list is inherited mainly from the deleted OWNERS file.

### CODE REVIEW

**Review by smoshiur1237 — COMMENTED** [review]
LGTM

**Review by lentzi90 — APPROVED** [review]
/approve

**Comment by lentzi90** [comment]
I think we will need approval from someone in each of the removed files

**Comment by kashifest** [comment]
> I think we will need approval from someone in each of the removed files

A couple of them have single entry who have left the project a while ago

**Comment by kashifest** [comment]
@digambar15 @ogelbukh if you are still around Metal3 please review this patch and leave an approve label if no objection with this.

**Review by Rozzii — APPROVED** [review]
/lgtm

**Pull request merged**
