### PR TITLE
Update Metal3-dev-env images

### PR DESCRIPTION
**Pull request by fmuyassarov**
Improve existing dev-env related images.

### CODE REVIEW

**Comment by fmuyassarov** [comment]
> s the



> nit: metal3-dev-env includes the switches, not only the vms

Sorry I didn't you. Do you want me to add switches on the picture ?

**Comment by maelk** [comment]
in your new image, you added an overall square for metal3-dev-env, but it does not contain the switches, that are actually part of it

**Comment by fmuyassarov** [comment]
> in your new image, you added an overall square for metal3-dev-env, but it does not contain the switches, that are actually part of it

Actually, four boxes on the left side of the overall square represent switches/bridges.

**Comment by maelk** [comment]
yes, but those boxes are not in the metal3-dev-env box, they are out of it. that was my point

**Comment by fmuyassarov** [comment]
> yes, but those boxes are not in the metal3-dev-env box, they are out of it. that was my point

Ah, ok. Will fix that.

**Comment by maelk** [comment]
/remove-lifecycle stale
I think we can still get this in, the change remains valid now
/approve

**Pull request merged**
