### PR TITLE
remove section about prow flake and workflows

### PR DESCRIPTION
**Pull request by tuminoid**
Prow flake about not merging workflow related PRs has been solved. Remove that.

(Issue was missing "workflow" permission for the metal3-io-bot token)

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/approve

**Comment by lentzi90** [comment]
Ow thought I had approvers rights. Oh well...
/lgtm

**Review by kashifest — APPROVED** [review]

**Review by furkatgofurov7 — APPROVED** [review]
This is a great find @tuminoid, thank you!

/approve

**Pull request merged**
