### PR TITLE
Triage proccess proposal

### PR DESCRIPTION
**Pull request by stbenjam**
This is my first pass at a triage process. Please have a look.

### CODE REVIEW

**Comment by maelk** [comment]
/lgtm

Maybe 180 days to close an issue without activity is a bit long ?

**Comment by stbenjam** [comment]
I updated this to adjust the stale time down as dicussed. I think this can land, and we can iterate as needed.

**Comment by stbenjam** [comment]
There's now a periodic job to mark and close stale issues: https://github.com/metal3-io/project-infra/pull/60

I updated the docs here to reflect that

**Pull request merged**
