### PR TITLE
fixed broken link reference to CRs

### PR DESCRIPTION
**Pull request by chibuikeIg**
### Which problem is this PR solving?

Closes issue: Fix dead links at crs_reference.md #446
Fixes: #446

### Description of the changes

Changed from https://github.com/metal3-io/metal3-dev-env/tree/master/crs to https://github.com/metal3-io/metal3-dev-env/tree/b5a53ecf9576c6deab81f692733782d4c5e8091a/crs

### How was this change tested?

Ensured the link works both on Browser and when clicked on the Doc.

### CODE REVIEW

**Comment by tuminoid** [comment]
Thanks for the PR! Please fix the DCO (sign-off the commit) and repush.

/ok-to-test
/cc @kashifest 

PTAL if the linking the last version of the CRS is the right link to replace the dead link, or was the content actually migrated elsewhere.
/hold

**Comment by dtantsur** [comment]
> PTAL if the linking the last version of the CRS is the right link to replace the dead link, or was the content actually migrated elsewhere.

I think it was migrated under the `base` subdirectory, and indeed we should link to the most recent version.

**Comment by kashifest** [comment]
I think this whole crs_reference.md file is obsolete, its still pointing to cluster-api-provider-baremetal! and v1a2 and v1a3 of apis, the crs are non existent in dev-env since I believe

**Comment by tuminoid** [comment]
We have two contradicting opinions it seems. It is the only file in the root of the repo and indeed looks obsolete, so insttead of fixing the link we could delete the whole file? @dtantsur @kashifest

**Pull request closed without merging**
