### PR TITLE
Add SUSE to ADOPTERS.md

### PR DESCRIPTION
**Pull request by hardys**
SUSE is working on Metal<sup>3</sup> integration as part of the Edge stack so adding here.

### CODE REVIEW

**Comment by tuminoid** [comment]
Thank you for becoming an adopter!

But hmm, where are bot messages and tests. 
/ok-to-test
/test all

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by Rozzii — APPROVED** [review]
/approve

**Review by lentzi90 — COMMENTED** [review]
/approve

**Pull request merged**
