### PR TITLE
Update the ALL-OWNERS file with up to date maintainer list

### PR DESCRIPTION
**Pull request by kashifest**
as the title says.

### CODE REVIEW

**Comment by kashifest** [comment]
cc @lentzi90 @Rozzii @tuminoid

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by Rozzii — APPROVED** [review]
/approve

**Comment by kashifest** [comment]
> /approve

/approve

**Review by lentzi90 — COMMENTED** [review]
/approve

**Pull request merged**
