### PR TITLE
update releasing.md

### PR DESCRIPTION
**Pull request by tuminoid**
We have made good progress on the releasing side. We have ironic-image releases now, as well as BMO is properly branched and released. Add relevant links to those documents, remove some of the TODO etc.

### CODE REVIEW

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Review by Sunnatillo — COMMENTED** [review]
LGTM

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by Rozzii — APPROVED** [review]
/lgtm

**Pull request merged**
