### PR TITLE
Add a Metal kubed banner design

### PR DESCRIPTION
**Pull request by codificat**
This is a proposed design for roll-up banners (80 x 200 cm) used in booths at conferences.

The design is based in the website [design mockup](https://marvelapp.com/527b7h7) presented [in the mail list](https://groups.google.com/forum/#!topic/metal3-dev/5El9eLau-oc) and uses the colors and font types specified there.

### CODE REVIEW

**Comment by russellb** [comment]
@maryshak1996 would you like to take a look at this one?

**Comment by maryshak1996** [comment]
@codificat @russellb 
This is definitely consistent with the current branding :) if you're looking for anything a bit more visually uhhhh 'rich', I'd be happy to jump in with some other ideas too!

**Comment by maryshak1996** [comment]
I threw something together with all of the assets that I have :) here's the LOW-RES review but I'm also attaching a PDF. Just another idea!
Screen Shot 2019-08-09 at 11 53 03 AM
[banner.pdf](https://github.com/metal3-io/metal3-docs/files/3487081/banner.pdf)

**Comment by russellb** [comment]
I like the additions you made, @maryshak1996 !

**Comment by codificat** [comment]
Apologies for the delay in following up here.

Many thanks for the design @maryshak1996 - it's much better than my poor attempt :wink: . I replaced my PDF with your version and removed my SVG. If you have the source file it might be good if you could send it in as well.

@russellb if you are ok with that design we'll go ahead and start using it ASAP, as we have a couple of events next month where we should have a banner.

Anyone else to review this?

**Comment by russellb** [comment]
looks good to me!  We can add the source SVG as a follow up.

/approve
/lgtm

**Pull request merged**
