### PR TITLE
update cspell spellchecker to v8.13.3

### PR DESCRIPTION
**Pull request by tuminoid**
It contains some bug fixes since previous version v8.9.0.

No fixes to spellings needed.

### CODE REVIEW

**Comment by tuminoid** [comment]
/hold
Need to update this in project-infra first.

**Review by Rozzii — COMMENTED** [review]
/approve

**Review by Rozzii — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
/test spellcheck
/unhold
Project-infra PR was merged.

**Review by kashifest — COMMENTED** [review]
/approve

**Pull request merged**
