### PR TITLE
proposed Inspection and Provisioning diagram

### PR DESCRIPTION
**Pull request by wrkode**
This PR addresses issue **https://github.com/metal3-io/metal3-docs/issues/258**
Please understand that I'm not (yet) strong with Metal3, but would something like the be technically correct?

### CODE REVIEW

**Comment by wrkode** [comment]
@Rozzii could you please review the diagram for technical correctness?

**Comment by Rozzii** [comment]
Thanks for the contribution @wrkode  I will check this soon.

**Comment by Rozzii** [comment]
@wrkode thanks fro creating this nice diagram, a few nits:
- Please highlight that the machine object comes from CAPI and that between the MAchine and the BMH there is a Metal3Machine object.
- You have mentioned  how the inspections is initiated so I would suggest mentioning how the provisioning is initiated (it starts when the image field gets populated)
- There is a typo in the "Start Provisioning" block "etal3" instead of "Metal3"
- If you used draw.io or some other code->image generator please attach the source code also.
cc @lentzi90 @mboukhalfa @kashifest

**Review by lentzi90 — COMMENTED** [review]
Thanks for working on this!
To keep things simple, I would advice to focus on just the Baremetal Operator level and the BareMetalHost resource for this diagram and not attempt to include Machines or Metal3Machines. Keeping that in mind, I would change the provisioning section so that the first two boxes are merged into one. There I would put something like

> Image information
> The spec.image field is filled with information about the desired provisioned state to start the provisioning process. This can be done by the user directly, or a controller such as CAPM3.

In the `Store Data` box it may be worth mentioning the [HardwareData CRD](https://github.com/metal3-io/metal3-docs/blob/main/design/baremetal-operator/hardwaredata_crd.md), I'm not sure.

**Comment by Rozzii** [comment]
> Thanks for working on this! To keep things simple, I would advice to focus on just the Baremetal Operator level and the BareMetalHost resource for this diagram and not attempt to include Machines or Metal3Machines. Keeping that in mind, I would change the provisioning section so that the first two boxes are merged into one. There I would put something like
> 
> > Image information
> > The spec.image field is filled with information about the desired provisioned state to start the provisioning process. This can be done by the user directly, or a controller such as CAPM3.
> 
> In the `Store Data` box it may be worth mentioning the [HardwareData CRD](https://github.com/metal3-io/metal3-docs/blob/main/design/baremetal-operator/hardwaredata_crd.md), I'm not sure.

I can get behind this also, then let's skip mentioning Metal3Machine and Machine objects.

**Comment by wrkode** [comment]
I'll have an updated version soon. thanks for the feedback folks.
for this I've use Excalidraw, but I want to use draw-io, so that I can share code.
expect a new version soon.

**Comment by dtantsur** [comment]
The diagram is mostly correct (I don't think inspection depends on the `online` field; there is a typo in metal3), but I'm curious what the purpose of it is. It's not linked in any document, and we probably have documents explaining the similar thing.

**Comment by wrkode** [comment]
> The diagram is mostly correct (I don't think inspection depends on the `online` field; there is a typo in metal3), but I'm curious what the purpose of it is. It's not linked in any document, and we probably have documents explaining the similar thing.

@dtantsur, I was working against https://github.com/metal3-io/metal3-docs/issues/258, but if you and team find this no more relevant, I can stop and close the PR. please do let me know though.

**Comment by wrkode** [comment]
@Rozzii I feel I do need to discuss this in the community/Project call. could you please let me know when this will happen next time?

**Comment by Rozzii** [comment]
@wrkode are you still interested to finish this?

**Pull request closed without merging**
