### PR TITLE
organize designs into component-specific folders

### PR DESCRIPTION
**Pull request by dhellmann**
We have enough designs that it makes sense to organize them a bit. This
will also allow us to add reviewer and approver permission for designs
for sub-components in a later pull request.

### CODE REVIEW

**Comment by russellb** [comment]
lgtm, but i'll give it some time for other input

**Comment by maelk** [comment]
just a question related to the proposals that were not moved, is it because they touch more than one component or are cross-repo ?

**Comment by maelk** [comment]
lgtm, just a question related to the proposals that were not moved, is it because they touch more than one component or are cross-repo ?

**Comment by dhellmann** [comment]
> lgtm, just a question related to the proposals that were not moved, is it because they touch more than one component or are cross-repo ?

Yes, those were either obviously related to multiple components or not obviously related to just one.

**Comment by dhellmann** [comment]
Are we ready to move ahead with this?

I also planned to add OWNERS files in each subdirectory based on the reviewers/approvers lists for the components they represent. I could do those as a separate PR,  several separate PRs, or part of this one. What do you think?

**Comment by russellb** [comment]
/lgtm

a single follow-up PR to seed OWNERS files seems OK to me

**Pull request merged**
