### PR TITLE
Adding IKEA IT AB to ADOPTERS

### PR DESCRIPTION
**Pull request by knfoo**
Adding IKEA IT AB to ADOPTERS

Signed-off-by: Karsten Nielsen <karsten.nielsen@ingka.ikea.com>

### CODE REVIEW

**Review by kashifest — APPROVED** [review]

**Review by furkatgofurov7 — COMMENTED** [review]
Thanks for the PR @knfoo!

/lgtm

**Comment by dtantsur** [comment]
/approve

This is great, welcome!

**Pull request merged**
